language: java
jdk:
- openjdk8
script: mvn clean verify
deploy:
  provider: heroku
  api_key:
    secure: q+Lb0WlfSBpfAvwvrZ4P5mr9nwAPSnQPYuZ+r+GAC97VPcgIOArYhrsr85XwEd381o91jaYxYaYF/QHmXfyH/qcivFjZw88vozgofro0I875P+DDE9h3dEEK4Gg0zqgQ7a64avkSNkSXI0yBkYoVR/L8vZYePtCd36obVJWJgyDn1EZkIy6pczju9KcuICaxFP/N0RR4GOBpBOU+bt6PVXuxOH0Bjn3/zeosvDIQeQnOABJE5yNSkXs8HLoBk/58rX0NLUv+/nIHNs4HBD9WT2dsAchECSh8JnTR5D81EGnufh0PqSVHoul2iGhDJjddnseJaM2VmO8iXGt+aSahHEJBSlKkULvBCefP6Hen9fiZAqX7nBNKjpjGIDW23474vZg05UCIR5IALrWcdGB1OCGsAg32toIoNrCd1x4GlATPLpbzdtTW0ADZBCVkBd8QmvGpiLuJS6gaOGGq76nFY5YNEFbBN+9ufQ1hoyolFZSdZZBA/IvEl947IDSFrXLTjw9/RKou/qOIt+zPRP1ihd8nbDtnjTjmRyK0k0u+ysKLxxh+h+dNdtM8mDRQH1iL6VFiqTiY6hyhV6N0jdH56hcedC/4iTOQYLRCLYtnJZ4aOQOq/5WiUv3Rw572Vwl0KnWU+KTX60pr1wYSCJeVvepstw95q60mShKf4LtIzdQ=
